[tool.poetry]
name = "dynamic"
version = "0.1.0"
description = ""
authors = ["Furqan Rydhan <furqan.rydhan@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.95.1"
uvicorn = "^0.21.1"
orjson = "^3.8.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
